# .streamlit/secrets.toml

[connections.snowflake]
account = "FOFOXOE-EEB51968"
user = "cashalot1"
password = "MyNewSecurePassword123!"
role = "ACCOUNTADMIN"
warehouse = "TRANSFORM_WH"
database = "COLORADO_CRIME_DB_PROD"
schema = "GOLD"
# If you use key-pair authentication instead of a password, you can use:
# private_key_file = "/path/to/rsa_key.pem"
# private_key_passphrase = "eakerian123"
