name: Deploy dbt Docs

on:
  push:
    branches:
      - main
    paths:
      - 'include/dbt/dbt_project/**'

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: dbt dependencies
        working-directory: ./include/dbt/dbt_project
        run: dbt deps

      - name: Generate Docs
        working-directory: ./include/dbt/dbt_project
        run: dbt docs generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./include/dbt/dbt_project/target
